services:
  - type: web
    name: school-management-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

  - type: web
    name: school-management-frontend
    env: static
    plan: free
    rootDir: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
