"""Add capacity, schedule, and location to Class model

Revision ID: ee702c92b339
Revises: 2749e43061de
Create Date: 2025-08-29 00:45:29.032842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee702c92b339'
down_revision = '2749e43061de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schedule', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('schedule')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
